project_name: clip

builds:
  - binary: clip
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - "386"

archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md

release:
  github:
    owner: mingrammer
    name: clip
  name_template: '{{.Tag}}'

brew:
  name: clip
  github:
    owner: mingrammer
    name: clip
  commit_author:
    name: mingrammer
    email: mingrammer@gmail.com
  folder: formula
  homepage: https://github.com/mingrammer/clip
  description: "A simple key-value store for clipboard"
  install: bin.install "clip"
  
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
